on: push

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'https://gitlab.com/czy29/workflow-bin.git'
        REMOTE_NAME: gitlab
        GIT_USERNAME: czy29
        GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'https://gitee.com/czy29/workflow-bin.git'
        REMOTE_NAME: gitee
        GIT_USERNAME: czy29
        GIT_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
